### ISSUE TITLE
Can't install from requirements file.

### ISSUE THREAD

**Issue by dpnova** [lextoumbourou/txes2#1]
pip 6.0.6
setuptools 11.0
gentoo + python 2.7

I get the error below when trying to install from a requirements file. Seems like it might be a pip version thing?

```
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "/tmp/pip-build-_zJiW4/txes2/setup.py", line 4, in <module>
    reqs = [str(ir.req) for ir in install_reqs]
  File "/home/dpn/.virtualenvs/inbox-api/lib/python2.7/site-packages/pip/req/req_file.py", line 19, in parse_requirements
    "parse_requirements() missing 1 required keyword argument: "
TypeError: parse_requirements() missing 1 required keyword argument: 'session'
Complete output from command python setup.py egg_info:
Traceback (most recent call last):

  File "<string>", line 20, in <module>

  File "/tmp/pip-build-_zJiW4/txes2/setup.py", line 4, in <module>

    reqs = [str(ir.req) for ir in install_reqs]

  File "/home/dpn/.virtualenvs/inbox-api/lib/python2.7/site-packages/pip/req/req_file.py", line 19, in parse_requirements

    "parse_requirements() missing 1 required keyword argument: "

TypeError: parse_requirements() missing 1 required keyword argument: 'session'
```

**Comment by lextoumbourou** [comment]
Sorry to take so long on this. I appear to be using an ancient version of Pip, after an upgrade I can replicate it.

I have no idea what a session is in the context of parsing a requirements file, but [other](https://github.com/jmcarp/robobrowser/pull/32/files) people are fixing it with a random UUID, so I might just do the same and call it a day. Fixing coming soon; stand by. :smile:
